version: '3.8'
services:
  technology-service:
    build: ./technology
    ports:
      - "8080:8080"
    networks:
      - on-class-network

  capacities-service:
    build: ./capacities
    ports:
      - "8081:8081"
    networks:
      - on-class-network

  bootcamps-service:
    build: ./bootcamps
    ports:
      - "8082:8082"
    networks:
      - on-class-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - technology-service
      - capacities-service
      - bootcamps-service
    networks:
      - on-class-network

networks:
  on-class-network:
    driver: bridge
